CREATE DATABASE EuroLeagues

GO

USE EuroLeagues

CREATE TABLE Leagues
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Teams
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL UNIQUE,
	City NVARCHAR(50) NOT NULL,
	LeagueId INT REFERENCES Leagues(Id) NOT NULL
)

CREATE TABLE Players
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	Position NVARCHAR(20) NOT NULL
)

CREATE TABLE Matches
(
	Id INT PRIMARY KEY IDENTITY,
    HomeTeamId INT REFERENCES Teams(Id) NOT NULL,
    AwayTeamId INT REFERENCES Teams(Id) NOT NULL,
	MatchDate DATETIME2 NOT NULL,
	HomeTeamGoals INT DEFAULT 0 NOT NULL,
	AwayTeamGoals INT DEFAULT 0 NOT NULL,
	LeagueId INT REFERENCES Leagues(Id) NOT NULL
)

CREATE TABLE PlayersTeams
(
	PlayerId INT REFERENCES Players(Id) NOT NULL,
	TeamId INT REFERENCES Teams(Id) NOT NULL
	PRIMARY KEY (PlayerId, TeamId)
)

CREATE TABLE PlayerStats
(
	PlayerId INT PRIMARY KEY REFERENCES Players(Id) NOT NULL,
	Goals INT DEFAULT 0 NOT NULL,
	Assists INT DEFAULT 0 NOT NULL
)

CREATE TABLE TeamStats
(
	TeamId INT PRIMARY KEY REFERENCES Teams(Id) NOT NULL,
	Wins INT DEFAULT 0 NOT NULL,
	Draws INT DEFAULT 0 NOT NULL,
	Losses INT DEFAULT 0 NOT NULL
)