CREATE DATABASE TechStore

CREATE TABLE Manufacturers 
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL,
	Country NVARCHAR(50) NOT NULL
)

CREATE TABLE Categories 
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(30) NOT NULL UNIQUE
)

CREATE TABLE Products 
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	Price Decimal(18,2) NOT NULL,
	Specifications NVARCHAR(1000),
	ManufacturerId INT REFERENCES Manufacturers(Id) NOT NULL,
	CategoryId INT REFERENCES Categories(Id) NOT NULL
)

CREATE TABLE Stores 
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	IsOnline BIT NOT NULL
)

CREATE TABLE StoresProducts 
(
	StoreId INT REFERENCES Stores(Id) NOT NULL,
	ProductId INT REFERENCES Products(Id) NOT NULL
	PRIMARY KEY(StoreId, ProductId)
)

CREATE TABLE Customers
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(80) NOT NULL,
	PhoneNumber NVARCHAR(20) NOT NULL,
	Email NVARCHAR(80)
)

CREATE TABLE Orders
(
	Id INT PRIMARY KEY IDENTITY,
	OrderDate DATETIME2 NOT NULL,
	CustomerId INT REFERENCES Customers(Id) NOT NULL,
	ProductId INT REFERENCES Products(Id) NOT NULL,
	StoreId INT REFERENCES Stores(Id) NOT NULL
)
