CREATE DATABASE ShoesApplicationDatabase

CREATE TABLE Users
(
	Id INT PRIMARY KEY IDENTITY,
	Username NVARCHAR(50) UNIQUE NOT NULL,
	FullName NVARCHAR(100) NOT NULL,
	PhoneNumber NVARCHAR(15),
	Email NVARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE Brands
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Sizes
(
	Id INT PRIMARY KEY IDENTITY,
	EU DECIMAL(5,2) NOT NULL,
	US DECIMAL(5,2) NOT NULL,
	UK DECIMAL(5,2) NOT NULL,
	CM DECIMAL(5,2) NOT NULL,
	[IN] DECIMAL(5,2) NOT NULL
)

CREATE TABLE Shoes
(
	Id INT PRIMARY KEY IDENTITY,
	Model NVARCHAR(30) NOT NULL,
	Price DECIMAL(10,2) NOT NULL,
	BrandId INT NOT NULL REFERENCES Brands (Id)
)

CREATE TABLE Orders
(
	Id INT PRIMARY KEY IDENTITY,
	ShoeId INT NOT NULL REFERENCES Shoes (Id),
	SizeId INT NOT NULL REFERENCES Sizes (Id),
	UserId INT NOT NULL REFERENCES Users (Id)
)

CREATE TABLE ShoesSizes
(
	ShoeId INT NOT NULL REFERENCES Shoes (Id),
	SizeId INT NOT NULL REFERENCES Sizes (Id),
	PRIMARY KEY (ShoeId, SizeId)
)